version: '3.8'

services:
  seguro-poliza-app:
    build: .
    container_name: seguro-poliza-app
    ports:
      - "3002:3000"
  
  nginx:
    image: nginx:latest
    container_name: nginx-seguro-poliza
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - seguro-poliza-app
